version: "3.9"

services:

  db-admin:
    container_name: db-admin
    image: adminer
    ports:
      - 8080:8080

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    command: -N 500
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

networks:
  default:
    name: stingray_test_network
